name: goreleaser

on:
 push:
    branches:
      - main

jobs:
  goreleaser:
    runs-on: ubuntu-latest-m
    steps:

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
