name: goreleaser

on:
  push:
    tags:
      - "*"

permissions:
  contents: write
  packages: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest-m
    steps:

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
